### ISSUE TITLE
cannot import name '_jsonl' from partially initialized module

### ISSUE THREAD

**Issue by SomebodySysop** [jruere/csv2jsonl#1]
This is a python / pip issue, but it's driving me crazy!

I'm trying to install the jsonl module using "pip install jsonl".  I've tried this on two ubuntu machines so far, and keep getting this error on BOTH machines:

```
root@ASUSET2410-Ubuntu:~# pip install jsonl
Collecting jsonl
  Downloading jsonl-1.6.tar.gz (9.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5lw5f9ew/jsonl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5lw5f9ew/jsonl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-5lw5f9ew/jsonl/pip-egg-info         cwd: /tmp/pip-install-5lw5f9ew/jsonl/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5lw5f9ew/jsonl/setup.py", line 5, in <module>
        import jsonl
      File "/tmp/pip-install-5lw5f9ew/jsonl/jsonl/__init__.py", line 19, in <module>
        from jsonl import _jsonl as jsonl
    ImportError: cannot import name '_jsonl' from partially initialized module 'jsonl' (most likely due to a circular import) (/tmp/pip-install-5lw5f9ew/jsonl/jsonl/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
Any suggestions on how to fix?

**Comment by jruere** [comment]
@SomebodySysop why make a comment here?

**Comment by SomebodySysop** [comment]
> @SomebodySysop why make a comment here?

Because I thought I might get some guidance here since this project requires jsonl.

**Comment by jruere** [comment]
It does not. It uses `jsonlines`.

Nevertheless, why not ask in that project's repo or community. If there isn't one, try a general Python mailing list, forum or similar.
